WizytowkaOnline/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using WizytowkaOnline.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WizytowkaOnline.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUslugaRepository _uslugaRepository;
        private readonly IOpiniaRepository _opiniaRepository;

        public HomeController(IUslugaRepository uslugaRepository, IOpiniaRepository opiniaRepository)
        {
            _uslugaRepository = uslugaRepository;
            _opiniaRepository = opiniaRepository;
        }

        public IActionResult Index()
        {
            ViewBag.Tytul = "Przeglad uslug";

            var uslugi = _uslugaRepository.PobierzWszystkieUslugi();

            return View(uslugi);
        }

        [HttpPost]
        public IActionResult Index(string fraza, string powiat, string kategoria)
        {
            ViewBag.Tytul = "Przeglad uslug";

            var uslugi = _uslugaRepository.PobierzWszystkieUslugi();

            if (!string.IsNullOrEmpty(fraza) || !string.IsNullOrEmpty(powiat) || !string.IsNullOrEmpty(kategoria))
            {
                return View(_uslugaRepository.FiltrujWszystkieUslugiUzytkownika(fraza, powiat, kategoria));
            }

            return View(uslugi);
        }

        public IActionResult Szczegoly(int id)
        {
            dynamic UslugiOpinie = new ExpandoObject();

            UslugiOpinie.Uslugi = _uslugaRepository.PobierzUslugePoId(id);
            UslugiOpinie.Opinie = _opiniaRepository.PobierzOpiniePoId(id);

            if (UslugiOpinie.Uslugi == null)
                return NotFound();

            return View(UslugiOpinie);
        }
    }
}

WizytowkaOnline/Controllers/OpiniaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WizytowkaOnline.Models;

namespace WizytowkaOnline.Controllers
{
    public class OpiniaController : Controller
    {
        private readonly IOpiniaRepository _opiniaRepository;
        private readonly IUslugaRepository _uslugaRepository;
        private readonly UserManager<IdentityUser> _userManager;

        public OpiniaController(IOpiniaRepository opiniaRepository, IUslugaRepository uslugaRepository, UserManager<IdentityUser> userManager)
        {
            _opiniaRepository = opiniaRepository;
            _uslugaRepository = uslugaRepository;
            _userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            ViewData["IdUslugi"] = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Opinia opinia)
        {
            if (ModelState.IsValid)
            {
                DateTime dataDodaniaOpini = DateTime.Now;
                opinia.DataDodaniaOpini = dataDodaniaOpini.ToString();

                if(opinia.NazwaUzytkownika == opinia.Email)
                {
                    var user = await _userManager.GetUserAsync(User);
                    opinia.Email = user.Email;
                }

                _opiniaRepository.DodajOpinie(opinia);
                return RedirectToAction("Szczegoly", "Home", new { id = opinia.IdUslugi});
            }
            return View(opinia);
        }

        public IActionResult UsunOpinie(int id)
        {
            var opinia = _opiniaRepository.PobierzJednaOpinie(id);

            return View(opinia);
        }

        [HttpPost, ActionName("UsunOpinie")]
        [ValidateAntiForgeryToken]
        public IActionResult UsunOpinieConfirmed(int id)
        {
            var opinia = _opiniaRepository.PobierzJednaOpinie(id);
            _opiniaRepository.UsunOpinie(opinia);

            return RedirectToAction("Szczegoly", "Home", new { id = opinia.IdUslugi });
        }
    }
}

WizytowkaOnline/Controllers/UslugaController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WizytowkaOnline.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WizytowkaOnline.Controllers
{
    public class UslugaController : Controller
    {
        private readonly IUslugaRepository _uslugaRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IOpiniaRepository _opiniaRepository;
        private IHostingEnvironment _env;

        public UslugaController(IUslugaRepository uslugaRepository, UserManager<IdentityUser> userManager, IOpiniaRepository opiniaRepository, IHostingEnvironment env)
        {
            _uslugaRepository = uslugaRepository;
            _userManager = userManager;
            _opiniaRepository = opiniaRepository;
            _env = env;
        }

        // GET: /<controller>/
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);

            return View(_uslugaRepository.PobierzWszystkieUslugiUzytkownika(userId));
        }

        public IActionResult Details(int id)
        {
            dynamic UslugiOpinie = new ExpandoObject();

            UslugiOpinie.Uslugi = _uslugaRepository.PobierzUslugePoId(id);
            UslugiOpinie.Opinie = _opiniaRepository.PobierzOpiniePoId(id);

            if (UslugiOpinie.Uslugi == null)
                return NotFound();

            return View(UslugiOpinie);
        }

        [Authorize]
        public IActionResult Create(string FileName)
        {
            var userId = _userManager.GetUserId(User);

            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/images/" + FileName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(Usluga usluga)
        {
            if(ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                DateTime dataDodaniaUslugi = DateTime.Now;

                usluga.DataDodaniaUslugi = dataDodaniaUslugi.ToString("d");

                usluga.IdUzytkownika =userId;
                _uslugaRepository.DodajUsluge(usluga);

                return RedirectToAction("Index");
            }
            return View(usluga);
        }

        public IActionResult Edit(int id, string FileName)
        {
            var usluga = _uslugaRepository.PobierzUslugePoId(id);

            if (usluga == null)
                return NotFound();

            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/images/" + FileName;
            else
                ViewBag.ImgPath = usluga.ZdjecieUrl;

            return View(usluga);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Usluga usluga)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);

                usluga.IdUzytkownika = userId;
                _uslugaRepository.EdytujUsluge(usluga);

                return RedirectToAction("Index");
            }
            return View(usluga);
        }

        public IActionResult Delete(int id)
        {
            var usluga = _uslugaRepository.PobierzUslugePoId(id);

            if (usluga == null)
                return NotFound();

            return View(usluga);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, string ZdjecieUrl)
        {
            var usluga = _uslugaRepository.PobierzUslugePoId(id);
            _uslugaRepository.UsunUsluge(usluga);

            if(ZdjecieUrl != null)
            {
                var webRoot = _env.WebRootPath;
                var filePath = Path.Combine(webRoot.ToString() + ZdjecieUrl);

                System.IO.File.Delete(filePath);
            }

            return RedirectToAction("Index");
        }

        [HttpPost("UploadFile")]
        public async Task<IActionResult> UploadFile(IFormCollection form)
        {
            var webRoot = _env.WebRootPath;

            var filePath = Path.Combine(webRoot.ToString() + "\\images\\" + form.Files[0].FileName);

            if(form.Files[0].FileName.Length > 0)
            {
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await form.Files[0].CopyToAsync(stream);
                }
            }

            if (Convert.ToString(form["Id"]) == string.Empty || Convert.ToString(form["Id"]) == "0")
            {
                return RedirectToAction(nameof(Create), new { FileName = Convert.ToString(form.Files[0].FileName) }); 
            }

            return RedirectToAction(nameof(Edit), new { FileName = Convert.ToString(form.Files[0].FileName) , id = Convert.ToString(form["Id"]) });
        }

        public IActionResult Zglos(int id)
        {
            var usluga = _uslugaRepository.PobierzUslugePoId(id);

            if (usluga == null)
                return NotFound();

            return View(usluga);
        }

        [HttpPost, ActionName("Zglos")]
        [ValidateAntiForgeryToken]
        public IActionResult ZgloszenieConfirm(int id)
        {
            var usluga = _uslugaRepository.PobierzUslugePoId(id);
            var zgloszenie = new ZgloszonaUsluga();

            zgloszenie.IdUslugi = usluga.Id;


            DateTime dataZgloszenia = DateTime.Now;
            zgloszenie.dataZgloszenia = dataZgloszenia.ToString();

            _uslugaRepository.ZglosUsluge(zgloszenie);

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles="admin")]
        public IActionResult AdminZgoszoneUslugi()
        {
            return View(_uslugaRepository.PobierzWszystkieZgloszoneUslugi());
        }
    }
}

WizytowkaOnline/Views/Home/Index.cshtml
@model IEnumerable<WizytowkaOnline.Models.Usluga>

    @foreach (var usluga in Model)
    {
<div class=" col-lg-8 col-md-12 container uslugi bg-light rounded shadow p-1 ">
    <div class="form-row">
        <div class="pl-1">
            @if (usluga.ZdjecieUrl == null)
            {
                <a asp-controller="Home" asp-action="Szczegoly" asp-route-id="@usluga.Id">
                    <img class="img-thumbnail" style="width: 140px; height: 140px;" src="~/images/brakZdjecia.jpg" alt="" />
                </a>
            }
            else
            {
                <a asp-controller="Home" asp-action="Szczegoly" asp-route-id="@usluga.Id">
                    <img class="img-thumbnail" style="width: 140px; height: 140px;" src="@usluga.ZdjecieUrl" alt="" />
                </a>
            }
        </div>
        <div class="figure-caption ml-3 mt-3">
            <h4>
                <a asp-controller="Home" asp-action="Szczegoly" asp-route-id="@usluga.Id">@usluga.NazwaUslugi</a>
            </h4>
            <div class="dropdown-divider"></div>
            <p>
                Kategoria: @usluga.Kategoria
            </p>
            <div class="form-row">
                @if (usluga.Miejscowosc != null)
                {
                <p>
                    <img src="~/icons/pin_1.png" alt="" width="18" height="18" title="pin" class="" />
                    @usluga.Powiat, @usluga.Miejscowosc
                </p>
                }
                else
                {
                <p>
                    <img src="~/icons/pin_1.png" alt="" width="18" height="18" title="pin" class="" />
                    @usluga.Powiat
                </p>
                }
                    <p class="ml-3">
                        <img src="~/icons/calendar.png" alt="" width="18" height="18" title="calendar" class="" />
                        @usluga.DataDodaniaUslugi
                    </p>
            </div>

        </div>
    </div>
</div>
    }

WizytowkaOnline/Views/Home/Szczegoly.cshtml
@model dynamic

<div class="container form-row text-light shadow-lg rounded-lg mt-3 bg-dark" >
    <div class="col-5 text-center p-5 align-middle">
        <h1>
            @if (Model.Uslugi.ZdjecieUrl == null)
            {
                <img class="img-fluid" style="width: 250px; height: 250px;" src="~/images/brakZdjecia.jpg" alt="LOGO" />
            }
            else
            {
                <img class="img-fluid" style="width: 250px; height: 250px;" src="@Model.Uslugi.ZdjecieUrl" alt="LOGO" />
            }
        </h1>
    </div>
    <div class="col-7 text-left pl-5 mt-5 mb-5 border-left">
        <h3 style="color: #01FDF6;">
            @Model.Uslugi.NazwaUslugi
        </h3>
        <h5 class="mb-4" style="color: #01FDF6;">
            @Model.Uslugi.Imie @Model.Uslugi.Nazwisko
        </h5>
        <h4>
            <img src="~/icons/pin_1.png" alt="" width="24" height="24" title="house" class="mr-2" />
            @Model.Uslugi.Miejscowosc
        </h4>
        <h4>
            <img src="~/icons/iphone.png" alt="" width="24" height="24" title="Phone" class="mr-2" />
            tel. @Model.Uslugi.nrTelefonu
        </h4>
        <h4>
            <img src="~/icons/mail.png" alt="" width="24" height="24" title="mail" class="mr-2" />
            email: @Model.Uslugi.email
        </h4>
        <h4>
            <img src="~/icons/browser.png" alt="" width="24" height="24" title="browser" class="mr-2" />
            @Model.Uslugi.stronaInternetowa
        </h4>
    </div>
</div>

<div class="container mt-3">
    <h4>
        Opis:
    </h4>
    <div class="container bg-light shadow p-2 rounded">
        @if (Model.Uslugi.Opis == null)
        {
            <span>Brak opisu...</span>
        }
        else
        {
            <span>@Model.Uslugi.Opis</span>
        }
    </div>
    <div class="text-right mt-1">
        <h3>
            <a asp-action="Index" class="btn btn-success">Powrót</a>
            <a asp-controller="Usluga" asp-action="Zglos" asp-route-id="@Model.Uslugi.Id" class="btn btn-warning">Zgłoś usługę</a>
            @if (User.IsInRole("admin"))
            {
                <a asp-controller="Usluga" asp-action="Delete" asp-route-id="@Model.Uslugi.Id" class="btn btn-danger">Usuń usługę</a>
            }
        </h3>
    </div>
</div>

<div class="container mt-5">
    <a class="btn btn-success border-light" asp-controller="Opinia" asp-action="Index" asp-route-id="@Model.Uslugi.Id">
        <img src="~/icons/pen_1.png" alt="" width="24" height="24" title="user" />
        Dodaj Opinię
    </a>
</div>

<div class="mt-3 container">
    @foreach (var opinia in Model.Opinie)
    {
        <div class="mb-3 col-8 bg-light rounded-lg shadow pt-1">
            <div class="bg-info rounded-lg p-1">
                <h5 class="mb-0">
                    <img src="~/icons/user.png" alt="" width="16" height="16" title="user" />
                    @opinia.NazwaUzytkownika
                    <small class="float-right">
                        @opinia.DataDodaniaOpini
                        <img src="~/icons/calendar.png" alt="" width="16" height="16" title="calendar" />
                        @if (User.IsInRole("admin"))
                        {
                            <a asp-controller="Opinia" asp-action="UsunOpinie" asp-route-id="@opinia.Id" class="text-danger">Usuń</a>
                        }
                    </small>
                </h5>
            </div>
            <div class="pb-2 pt-2">
                <span>@opinia.Wiadomosc</span>
            </div>
        </div>
    }
</div>